#/bin/sh
MQ_DEFAULT_INSTALLATION_PATH=/opt/mqm
MQ_INSTALLATION_PATH=${MQ_INSTALLATION_PATH:=$MQ_DEFAULT_INSTALLATION_PATH}
. $MQ_INSTALLATION_PATH/bin/setmqenv

LOG_DIR=$MQ_DATA_PATH/log
DATA_DIRECTORY=$MQ_DATA_PATH/qmgrs

DQ_CLIENTQM_NAME=PERF1
DQ_CLIENTQM_HOST=mqperfx210
DQ_CLIENTQM_PORT=1500
DQ_CLIENTQM_LOG_DIR=$LOG_DIR
DQ_CLIENTQM_DATA_DIRECTORY=$DATA_DIRECTORY
#
DQ_SERVERQM_NAME=PERF0
DQ_SERVERQM_HOST=mqperfxw10
DQ_SERVERQM_PORT=1501
DQ_SERVERQM_LOG_DIR=$LOG_DIR
DQ_SERVERQM_DATA_DIRECTORY=$DATA_DIRECTORY

DQ_CHANNELS=10
DQ_REMOTE_QUEUE_PAIRS=20
DQ_BATCH_SIZE=50

#For 2K Message Size
DQ_LOG_PRIMARY_FILES=16
DQ_QUEUE_BUFF_SIZE=10485760

#For 20K Message Size
#DQ_LOG_PRIMARY_FILES=24
#DQ_QUEUE_BUFF_SIZE=10485760


#For 200K,2M Message Size
#DQ_LOG_PRIMARY_FILES=32
#DQ_QUEUE_BUFF_SIZE=104857600
