#/bin/sh
#For multiple QMs
QM_NAME_PREFIX=PERF
#For Single QM
QM_NAME=PERF01
LISTENER_PORT=31414

#WIP
MQ_DEFAULT_INSTALLATION_PATH=/home/franz/MQ/issues/1894-takeover-on-agent-abend/i
MQ_INSTALLATION_PATH=${MQ_INSTALLATION_PATH:=$MQ_DEFAULT_INSTALLATION_PATH}
MQ_DATA_PATH=${MQ_DEFAULT_INSTALLATION}/opt/mqm
# WIP . $MQ_INSTALLATION_PATH/bin/setmqenv
. ${MQ_INSTALLATION_PATH}/var/mqm/mqprofile

echo "MQ_DEFAULT_INSTALLATION_PATH: $MQ_DEFAULT_INSTALLATION_PATH"
echo "MQ_INSTALLATION_PATH: $MQ_INSTALLATION_PATH"
echo "MQ_DATA_PATH: $MQ_DATA_PATH"

#Override the following two variables for non-default file locations
LOG_DIR=$MQ_INSTALLATION_PATH/opt/mqm/log

DATA_DIRECTORY=$MQ_INSTALLATION_PATH/var/mqm

#For 2K Message Size
LOG_PRIMARY_FILES=16
QUEUE_BUFF_SIZE=10485760

#For 20K Message Size
#LOG_PRIMARY_FILES=24
#QUEUE_BUFF_SIZE=10485760

#For 200K,2M Message Size
#LOG_PRIMARY_FILES=32
#QUEUE_BUFF_SIZE=104857600
